src/Entity/Films.php
<?php

namespace App\Entity;

use App\Repository\FilmsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmsRepository::class)]
class Films
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 500)]
    private ?string $description = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $age_mini = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $note = null;

    #[ORM\Column]
    private ?bool $coup_coeur = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_sortie = null;

    #[ORM\Column]
    private array $genre = [];

    #[ORM\Column(length: 255)]
    private ?string $affiche = null;

    #[ORM\Column]
    private ?int $duree = null;

    /**
     * @var Collection<int, Seances>
     */
    #[ORM\OneToMany(targetEntity: Seances::class, mappedBy: 'Films')]
    private Collection $films;

    public function __construct()
    {
        $this->films = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAgeMini(): ?int
    {
        return $this->age_mini;
    }

    public function setAgeMini(int $age_mini): static
    {
        $this->age_mini = $age_mini;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function isCoupCoeur(): ?bool
    {
        return $this->coup_coeur;
    }

    public function setCoupCoeur(bool $coup_coeur): static
    {
        $this->coup_coeur = $coup_coeur;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): static
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function getGenre(): array
    {
        return $this->genre;
    }

    public function setGenre(array $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche): static
    {
        $this->affiche = $affiche;

        return $this;
    }

    //emplacement des images

    public function getAffichePath(): string
    {
        return $this->affiche ? '/affiches/' . $this->affiche : '/affiches/default.jpg';
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    /**
     * @return Collection<int, Seances>
     */
    public function getFilms(): Collection
    {
        return $this->films;
    }

    public function addFilm(Seances $film): static
    {
        if (!$this->films->contains($film)) {
            $this->films->add($film);
            $film->setFilms($this);
        }

        return $this;
    }

    public function removeFilm(Seances $film): static
    {
        if ($this->films->removeElement($film)) {
            // set the owning side to null (unless already changed)
            if ($film->getFilms() === $this) {
                $film->setFilms(null);
            }
        }

        return $this;
    }
}

src/Form/FilmsType.php
<?php

namespace App\Form;

use App\Entity\Films;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;

class FilmsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class)
            ->add('description', TextareaType::class)
            ->add('age_mini', IntegerType::class, [
                'attr' => [
                    'min' => 1,
                    'max' => 18
                ]
            ])
            //->add('note')
            ->add('coup_coeur', CheckboxType::class, [
                'required' => false,
            ])
            ->add('date_sortie', null, [
                'widget' => 'single_text',
            ])
            ->add('duree', IntegerType::class)
            ->add('Genre', ChoiceType::class, [
                'choices' => [
                    'Action' => 'action',
                    'Comédie' => 'comedy',
                    'ScienceFiction' => 'sf'
                ],
                'multiple' => true
            ])
            ->add('affiche', FileType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez carger une affiche de film.',
                    ]),
                    new File([
                        'maxSize' => '1M',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/webp'
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger un fichier au format WEBP, JPEG ou PNG.'

                    ])
                ]
            ])
            ->add('Submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Films::class,
        ]);
    }
}

src/Controller/FilmsController.php
<?php

namespace App\Controller;

use App\Entity\Films;
use App\Form\FilmsType;
use App\Repository\FilmsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/films')]
final class FilmsController extends AbstractController
{
    #[Route(name: 'app_films_index', methods: ['GET'])]
    public function index(FilmsRepository $filmsRepository): Response
    {
        $lastWednesday = new \Datetime('last wednesday');

        // Récupérer les films depuis cette date
        $films = $filmsRepository->createQueryBuilder('f')
            ->where('f.date_sortie >= :lastWednesday')
            ->setParameter('lastWednesday', $lastWednesday)
            ->orderBy('f.date_sortie', 'DESC')
            ->getQuery()
            ->getResult();
        return $this->render('films/index.html.twig', [
            //'films' => $filmsRepository->findAll(),
            'films' => $films,
        ]);
    }

    #[Route('/new', name: 'app_films_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $film = new Films();
        $form = $this->createForm(FilmsType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //récupération de l'affiche 

            $afficheFile = $form->get('affiche')->getData();
            if ($afficheFile) {
                $uploadDirectory = $this->getParameter('kernel.project_dir') . '/public/affiches';
                $newFilename = uniqid() . '.' . $afficheFile->guessExtension();
                $afficheFile->move($uploadDirectory, $newFilename);

                // Mise à jour de l'entité avec le nom de fichier
                $film->setAffiche($newFilename);
                $entityManager->persist($film);
                $entityManager->flush();

                return $this->redirectToRoute('app_films_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->render('films/new.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_films_show', methods: ['GET'])]
    public function show(Films $film): Response
    {
        return $this->render('films/show.html.twig', [
            'film' => $film,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_films_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Films $film, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FilmsType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_films_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('films/edit.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_films_delete', methods: ['POST'])]
    public function delete(Request $request, Films $film, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $film->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($film);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_films_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/films/_delete_form.html.twig
<form method="post" action="{{ path('app_films_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn">Delete</button>
</form>

templates/films/_form.html.twig
{{ form_start(form) }}
{# {{ form_widget(form) }} 
<button class="btn">{{ button_label|default('Save') }}</button>#}
{{ form_end(form) }}

templates/films/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Films{% endblock %}

{% block body %}
    <h1>Edit Films</h1>

    {{ include('films/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_films_index') }}">back to list</a>

    {{ include('films/_delete_form.html.twig') }}
{% endblock %}

templates/films/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Films index
{% endblock %}

{% block body %}
	<h1>Films index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Titre</th>
				<th>Description</th>
				<th>Age_mini</th>
				<th>Note</th>
				<th>Coup_coeur</th>
				<th>Date_sortie</th>
				<th>Genre</th>
				<th>Affiche</th>
				<th>Duree</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for film in films %}
				<tr>
					<td>{{ film.id }}</td>
					<td>{{ film.titre }}</td>
					<td>{{ film.description }}</td>
					<td>{{ film.ageMini }}</td>
					<td>{{ film.note }}</td>
					<td>{{ film.coupCoeur ? 'Yes' : 'No' }}</td>
					<td>{{ film.dateSortie ? film.dateSortie|date('Y-m-d') : '' }}</td>
					<td>{{ film.genre ? film.genre|json_encode:'' }}</td>
					<td><img src="{{ asset(film.getAffichePath()) }}" alt="Affiche du film" style="max-width: 105px; max-height: 149px;"></td>
					<td>{{ film.duree }}</td>
					<td>
						<a href="{{ path('app_films_show', {'id': film.id}) }}">show</a>
						<a href="{{ path('app_films_edit', {'id': film.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="11">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_films_new') }}">Create new</a>
{% endblock %}

templates/films/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Films{% endblock %}

{% block body %}
    <h1>Create new Films</h1>

    {{ include('films/_form.html.twig') }}

    <a href="{{ path('app_films_index') }}">back to list</a>
{% endblock %}

templates/films/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Films
{% endblock %}

{% block body %}
	<h1>Films</h1>

	<div class="show">
		<div>
			<table>
				<tbody>

					<tr>
						<th>Id</th>
						<td>{{ film.id }}</td>
					</tr>
					<tr>
						<th>Titre</th>
						<td>{{ film.titre }}</td>
					</tr>
					<tr>
						<th>Description</th>
						<td>{{ film.description }}</td>
					</tr>
					<tr>
						<th>Age_mini</th>
						<td>{{ film.ageMini }}</td>
					</tr>
					<tr>
						<th>Note</th>
						<td>{{ film.note }}</td>
					</tr>
					<tr>
						<th>Coup_coeur</th>
						<td>{{ film.coupCoeur ? 'Yes' : 'No' }}</td>
					</tr>
					<tr>
						<th>Date_sortie</th>
						<td>{{ film.dateSortie ? film.dateSortie|date('Y-m-d') : '' }}</td>
					</tr>
					<tr>
						<th>Genre</th>
						<td>{{ film.genre ? film.genre|json_encode:'' }}</td>
					</tr>
					<tr>
						<th>Duree</th>
						<td>{{ film.duree }}</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div>
			<img src="{{ asset(film.getAffichePath()) }}" alt="Affiche du film" style="max-width: 210px; max-height: 297px;">
		</div>
	</div>


	<a href="{{ path('app_films_index') }}">back to list</a>

	<a href="{{ path('app_films_edit', {'id': film.id}) }}">edit</a>

	{{ include('films/_delete_form.html.twig') }}
{% endblock %}